### ISSUE TITLE
Unable to require metricsgraphics

### ISSUE THREAD

**Issue by rgbkrk** [rgbkrk/metrics-graphics-jupyter#1]
Requiring metricsgraphics is a bit awkward as it does a `require` (through `define`) on relative resources for D3 and jQuery.

![screen shot 2015-03-08 at 12 08 03 am](https://cloud.githubusercontent.com/assets/836375/6544821/419a2ebe-c527-11e4-8ca9-d0d52958cb44.png)

It ends up trying to pull it from `/static/d3.js`. If I change the vendorized metricsgraphics.js to do a different configuration for where d3 comes from:

``` JavaScript
require.config({paths: {d3: "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.0/d3.min"}});
```

Then d3 doesn't get loaded properly.

Any tips @jdfreder?

**Comment by rgbkrk** [comment]
To get around this for now I cheated and put D3 in the static assets of IPython itself (since I have it symlinked for dev).

**Comment by jdfreder** [comment]
You are the CORs master, could it be a CORs problem?  Seems to work here: http://jsfiddle.net/kmaxb9t3/1/ .

**Comment by rgbkrk** [comment]
Somehow it doesn't get passed down and uses `define`.

This is how metricsgraphics loads D3:

``` JavaScript
(function() {
    "use strict";
    (function(root, factory) {
      if (typeof define === 'function' && define.amd) {
        define(['d3', 'jquery'], factory);
      } else if (typeof exports === 'object') {
        module.exports = factory(require('d3'), require('jquery'));
      } else {
        root.MG = factory(root.d3, root.jQuery);
      }
    }(this, function(d3, $) {
    window.MG = {version: '2.2.1'};
```

When I traced this, it hit the line

``` JavaScript
define(['d3', 'jquery'], factory);
```

**Comment by jdfreder** [comment]
Define seems to work too:

http://jsfiddle.net/kmaxb9t3/3/

Maybe it's something with Jupyter's require config.

**Comment by jdfreder** [comment]
Although it works for me here: https://github.com/jdfreder/ipython-d3networkx/blob/master/d3networkx/widget.js
